plugins {
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
}

group = 'com.quizme'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':auth')
    implementation project(':common')
    implementation project(':business')
}

subprojects {
    apply plugin: 'java-library'

    group = 'com.quizme'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation platform('org.springframework.boot:spring-boot-dependencies:4.0.1')
    }

    // avoid "(certificate_unknown) PKIX" errors in integration tests by providing truststore
    tasks.withType(Test).tap {
        configureEach {
            systemProperty "javax.net.ssl.trustStore", "$rootDir/src/test/resources/truststore.p12"
            systemProperty "javax.net.ssl.trustStoreType", "PKCS12"
            systemProperty "javax.net.ssl.trustStorePassword", "somepassword"
        }
    }
}