services:
  consul-server-1:
    image: hashicorp/consul:2.0
    container_name: consul-server-1
    restart: always
    # -server -> tells binary to start in server mode (server agent)
    # -bootstrap-expect -> tells the servers not to form a leader until the expected 3 servers are up
    # -client=0.0.0.0, only accepted for local development, but unsafe in production to bind to 0.0.0.0
    #   should be replaced by VPC ip instead.
    # -ui -> to be able to access localhost:8500/ui
    command: "agent -server -node=server-1 -bootstrap-expect=3 -client=0.0.0.0 -ui" #
    ports:
      - "8500:8500" # Expose the UI and HTTP API from the first server to your host machine

  consul-server-2:
    image: hashicorp/consul:2.0
    container_name: consul-server-2
    restart: always
    command: "agent -server -node=server-2 -retry-join=consul-server-1 -client=0.0.0.0"
    depends_on:
      - consul-server-1

  consul-server-3:
    image: hashicorp/consul:2.0
    container_name: consul-server-3
    restart: always
    command: "agent -server -node=server-3 -retry-join=consul-server-1 -client=0.0.0.0"
    depends_on:
      - consul-server-1

  redis:
    image: redis:8.6.3
    container_name: redis
    ports:
      - '6379:6379'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.155.0
    container_name: otel-collector
    command: [ "--config=/etc/otel/collector-config.yml" ]
    volumes:
      - ./docker-volume/collector-config.yaml:/etc/otel/collector-config.yml
    ports:
      - "4317:4317" # grpc
      - "4318:4318" # http
      - "9464:9464" # export to prometheus
  loki:
    image: grafana/loki:3.7.3
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./docker-volume/loki.yaml:/etc/loki/loki-config.yaml
      - loki-data:/etc/loki
    depends_on:
      - otel-collector
  tempo:
    image: grafana/tempo:2.9.3
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker-volume/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    depends_on:
      - otel-collector
  prometheus:
    image: prom/prometheus:v3.13.0
    container_name: prometheus
    volumes:
      - ./docker-volume/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus # persist prometheus metrics
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
  grafana:
    image: grafana/grafana:13.1.0
    container_name: grafana
    volumes:
      - ./docker-volume/grafana/datasources:/etc/grafana/provisioning/datasources # mount and load initial datasources on startup
      - ./docker-volume/grafana/dashboards:/etc/grafana/provisioning/dashboards # mount and load initial dashbaord on startup
      - grafana-data:/var/lib/grafana # save changes made to dashbaord
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - prometheus
      - tempo

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  tempo-data: