plugins {
    id "java"
    id "org.springframework.boot" version "4.0.1"
    id "io.spring.dependency-management" version "1.1.7"
}

group = "com"
version = "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {

    implementation project(":common")

    implementation "org.springframework.boot:spring-boot-starter-oauth2-client"
    // For hashing passwords
    implementation "org.springframework.security:spring-security-crypto"
    runtimeOnly "org.bouncycastle:bcprov-jdk18on:1.84"

    testImplementation platform("org.junit:junit-bom:5.10.0")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.test {
    useJUnitPlatform()
}