spring:
  application:
    name: quizme
  profiles:
    active: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: validate # validate the created tables schema against the entities, app won't start if they don't match
  #  sql:
  #    init:
  #      mode: always # always run schema and data scripts on startup

  ssl:
    bundle:
      jks:
        sslbundle:
          key:
            alias: ${SSL_CERT_ALIAS}
          keystore:
            location: ${SSL_CERT_LOCATION}
            password: ${SSL_CERT_PW}
            type: PKCS12
server:
  ssl:
    bundle: sslbundle

app:
  auth:
    pepper: ${PEPPER_STRING}