spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop # don't run schema.sql on startup as it is postgres specific, instead let hibernate create the schema based on entities
  sql:
    init:
      mode: never # related to above comment, don't run any sql scripts on startup

  ssl:
    bundle:
      jks:
        sslbundle:
          key:
            alias: te-9f6319ad-c6eb-4203-bf3f-8f4f7b2c1ec0
          keystore:
            location: classpath:quizme-cert.pfx
            password: somepassword

app:
  auth:
    pepper: somepepperfortests
    jwt:
      secret: 793d83ccec5e1b5df2635f318a036d1d4734d64d2238e1e8e4ad9344ac99e509
      access_token_duration: 3600000
      refresh_token_duration: 604800000