CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME users_seq) PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE user_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME user_credentials_seq) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT fk_credential_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE external_identities(
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME user_identity_seq) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL, -- 'Google', 'GitHub', 'Microsoft', etc.
    provider_user_id VARCHAR(255) NOT NULL,
    provider_username VARCHAR(255),
    provider_user_email VARCHAR(255),
    CONSTRAINT fk_identity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME categories_seq) PRIMARY KEY,
    user_id bigint NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT user_category UNIQUE (user_id, name),
    CONSTRAINT fk_category_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME questions_seq) PRIMARY KEY,
    user_id bigint NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_question_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE questions_categories (
    question_id bigint,
    category_id bigint,
    PRIMARY KEY (question_id, category_id),
    CONSTRAINT fk_qc_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    CONSTRAINT fk_qc_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);