spring:
  config:
    import: "classpath:observability.yaml"
  application:
    name: quizme
  profiles:
    active: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: validate # validate the created tables schema against the entities, app won't start if they don't match
    properties:
      hibernate:
        dialect: com.quizme.config.CustomPostgreSQLDialect
  cloud:
    consul:
      discovery:
        scheme: https # backend configured to accepts https only, not http
#  sql:
#    init:
#      mode: always # always run schema and data scripts on startup

  ssl:
    bundle:
      jks:
        sslbundle:
          key:
            alias: ${SSL_CERT_ALIAS}
          keystore:
            location: ${SSL_CERT_LOCATION}
            password: ${SSL_CERT_PW}
            type: PKCS12
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
server:
  ssl:
    bundle: sslbundle

app:
  auth:
    pepper: ${PEPPER_STRING}
    jwt:
      secret: ${JWT_SECRET}
      access_token_duration: ${JWT_ACCESS_DURATION} # validity of access token in milliseconds
      refresh_token_duration: ${JWT_REFRESH_DURATION}
  frontend_url: ${FRONTEND_URL}
  kafka:
    url: ${KAFKA_URL}