plugins {
    id 'maven-publish'
    id 'java-test-fixtures' // to expose IntegrationTest
    id 'java-library'
}

group = "com.quizme"
version = "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    api "org.springframework.boot:spring-boot-starter-data-jpa"
    api "org.springframework.boot:spring-boot-starter-webmvc"
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.boot:spring-boot-starter-data-redis'

    api 'org.springframework.boot:spring-boot-starter-restclient'

    // JWT
    api 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // observability
    api 'org.springframework.boot:spring-boot-starter-opentelemetry'
    api 'io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:2.28.1-alpha'

    runtimeOnly 'org.postgresql:postgresql:42.7.8'

    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation platform("org.junit:junit-bom:5.10.0")
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    testFixturesImplementation project(':app') // to be able to import QuizmeApplication in integration tests
    testFixturesImplementation platform('org.springframework.boot:spring-boot-dependencies:4.0.1')
    testFixturesImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    // creating test containers in tests
    testFixturesImplementation platform('org.testcontainers:testcontainers-bom:1.21.4')
    testFixturesImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testFixturesImplementation 'org.testcontainers:postgresql'
    testFixturesImplementation 'com.redis.testcontainers:testcontainers-redis:1.6.4'
}

tasks.test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'com.quizme'
            artifactId = 'common'
            version = '0.0.1-SNAPSHOT'
        }
    }
    repositories {
        mavenLocal() // publishes to ~/.m2
    }
}